### ISSUE TITLE
Add ImgLib2 to the classpath of scripts

### ISSUE THREAD

**Issue by stelfrich** [knime-ip/knip-scripting#81] opened 2016-06-21 11:44 UTC
```java
import net.imglib2.*;
```
does not compile properly with `error: package net.imglib2 does not exist`.

**Comment by stelfrich** [comment] 2016-06-21 14:06
The following script should compile without problems:

```java
package script;

import net.imglib2.type.numeric.NumericType;

import org.scijava.command.Command;

@Plugin(type = Command.class)
public class TestPlugin<T extends NumericType<T>> implements Command { 

        @Override
        public void run() {
		
        }

}
```

**Comment by dietzc** [comment] 2016-06-21 14:20
Does it in ImageJ2?

**Comment by stelfrich** [comment] 2016-06-22 07:39
@dietzc It does not work when I use the Script Editor (which is the equivalent to the scripting node?) but works when implemented in a standalone Maven project.

However, when using the Script Editor at least ImgLib2 is in the classpath. But it seems that even if we are able to tackle that issue, there is another issue touching on that subject: https://github.com/scijava/scripting-java/issues/7

**Comment by dietzc** [comment] 2016-06-22 10:15
isn't there an import of `Plugin` missing in your script?

**Comment by stelfrich** [comment] 2016-06-22 10:48
> isn't there an import of Plugin missing in your script?

That's actually true. Here is an example that should compile without problems:

```java
package script;

import net.imglib2.*;

import org.scijava.plugin.Plugin;
import org.scijava.command.Command;

@Plugin(type = Command.class)
public class Script implements Command {
	
	@Override
	public void run() {
		
	}
}
```

**Comment by ctrueden** [comment] 2016-06-22 14:06
> Here is an example that should compile without problems

Here is an example that _does_ compile without problems (I tested it):
```java
import net.imglib2.*;

import org.scijava.plugin.Parameter;
import org.scijava.plugin.Plugin;
import org.scijava.command.Command;
import org.scijava.ui.UIService;

@Plugin(type = Command.class)
public class Script implements Command {

	@Parameter
	UIService ui;
	
    @Override
    public void run() {
		RandomAccessibleInterval rai = null;
    	ui.showDialog("Hello!");
    }
}
```
But with the latest Java 8 version of Fiji, it only works if you first delete `jars/tools.jar` and `jars/javac.jar` from your installation before launching ImageJ. There is currently a limitation in the Updater where you cannot mark a file obsolete on a downstream update site, so we cannot remove these files from the perspective of the Java-8 update site. We could delete them from the ImageJ and Fiji update sites respectively, but it would break the Java support for the Java 6 version of ImageJ2.

**Comment by dietzc** [comment] 2016-06-22 21:08
@gab1one any comments? Does this work for us?

**Comment by dietzc** [comment] 2016-06-26 01:02
I can confirm: 
```
package script;

import org.scijava.plugin.Parameter;
import org.scijava.plugin.Plugin;
import org.scijava.ItemIO;
import org.scijava.command.Command;
import org.scijava.plugin.Attr;
import net.imglib2.img.Img;

@Plugin(type = Command.class)
public class Script implements Command { 

	@Parameter(type = ItemIO.INPUT, attrs = {@Attr(name = "columnSelect", value = "true"), @Attr(name= "defaultColumn", value = "Img")})
	private Img img;
	
	/*
	 * Parameters
	 * 
	 * Define inputs and/or outputs of your script.
	 * By annotating a member with
	 *  -> @Parameter(type = ItemIO.INPUT) you define an input
	 *	-> @Parameter(type = ItemIO.OUTPUT) you define an output
	 *	-> @Parameter(type = ItemIO.BOTH) you define a member to
	 *	   be both input and output.
	 */
	
	public void run() {
	
		/*
		 * Put code which evaluates the parameters here.
		 * 
		 * To output something to a table row, you merely need to
		 * set output parameters. They will be automatically result
		 * in column in the output table.
		 */
		
	}
}
```
Doesn't work either.

I think it's because we don't explicitly have any plugin providing those classes to the scripting (e.g. by re-exporting them. `ImgPlus` can be imported because of some magical buddy class loading). We could however create a plugin which comprises all of the interesting bundles (`Imglib2`, `ImageJ-Ops` etc), registers itself as buddy and exports all dependencies.

**Comment by dietzc** [comment] 2016-06-28 16:02
should be working with the org.knime.knip.scripting bundle in the repo. @stelfrich can you confirm and close the issue?

**Closed by dietzc** 2016-06-28 16:02 UTC
Labels: bug
